// import type {
//   // CompOffCredit,
//   // CompOffCreditRequest,
//   // HolidayCalendar,
//   // LeaveBalance,
//   // LeaveLedgerEntry,
//   // LeavePolicy,
//   // LeaveRequest,
//   // LeaveType,
//   PayrollLeaveInput,
//   // TeamCalendarEntry,
//   // WorkCalendar,
// } from "./leaveTypes";

// export const mockLeaveTypes: LeaveType[] = [
//   {
//     id: "lt-el",
//     code: "EL",
//     name: "Earned Leave",
//     description: "Annual paid leave accrued monthly.",
//     paid: true,
//     enabled: true,
//     color: "#2563eb",
//     maxDaysPerRequest: 15,
//   },
//   {
//     id: "lt-sl",
//     code: "SL",
//     name: "Sick Leave",
//     description: "Medical leave for illness and recovery.",
//     paid: true,
//     enabled: true,
//     color: "#16a34a",
//     maxDaysPerRequest: 7,
//     requiresDocumentAfterDays: 2,
//   },
//   {
//     id: "lt-cl",
//     code: "CL",
//     name: "Casual Leave",
//     description: "Short planned or unplanned personal leave.",
//     paid: true,
//     enabled: true,
//     color: "#e16a3d",
//     maxDaysPerRequest: 3,
//   },
//   {
//     id: "lt-co",
//     code: "CO",
//     name: "Comp Off",
//     description: "Compensatory off against approved extra work.",
//     paid: true,
//     enabled: true,
//     color: "#7c3aed",
//     maxDaysPerRequest: 2,
//   },
//   {
//     id: "lt-lop",
//     code: "LOP",
//     name: "Loss Of Pay",
//     description: "Unpaid leave when balance is unavailable or policy requires it.",
//     paid: false,
//     enabled: true,
//     color: "#dc2626",
//   },
//   {
//     id: "lt-oh",
//     code: "OH",
//     name: "Optional Holiday",
//     description: "Optional holiday entitlement for regional or festival holidays.",
//     paid: true,
//     enabled: true,
//     color: "#0891b2",
//     maxDaysPerRequest: 1,
//   },
// ];

// export const mockLeaveRequests: LeaveRequest[] = [
//   {
//     id: "lv-1001",
//     employeeId: "emp-100",
//     employeeCode: "PNI001",
//     employeeName: "Aarav Menon",
//     department: "Engineering",
//     location: "Bengaluru",
//     managerId: "emp-200",
//     managerName: "Nisha Rao",
//     leaveTypeId: "lt-el",
//     leaveTypeCode: "EL",
//     leaveTypeName: "Earned Leave",
//     fromDate: "2026-05-18",
//     toDate: "2026-05-20",
//     dayType: "FULL_DAY",
//     days: 3,
//     reason: "Family function in Kochi",
//     status: "PENDING",
//     appliedOn: "2026-05-05",
//   },
//   {
//     id: "lv-1002",
//     employeeId: "emp-100",
//     employeeCode: "PNI001",
//     employeeName: "Aarav Menon",
//     department: "Engineering",
//     location: "Bengaluru",
//     managerId: "emp-200",
//     managerName: "Nisha Rao",
//     leaveTypeId: "lt-sl",
//     leaveTypeCode: "SL",
//     leaveTypeName: "Sick Leave",
//     fromDate: "2026-05-07",
//     toDate: "2026-05-07",
//     dayType: "FULL_DAY",
//     days: 1,
//     reason: "Fever",
//     status: "APPROVED",
//     appliedOn: "2026-05-07",
//     approverRemarks: "Approved. Take care.",
//   },
//   {
//     id: "lv-1003",
//     employeeId: "emp-100",
//     employeeCode: "PNI001",
//     employeeName: "Aarav Menon",
//     department: "Engineering",
//     location: "Bengaluru",
//     managerId: "emp-200",
//     managerName: "Nisha Rao",
//     leaveTypeId: "lt-cl",
//     leaveTypeCode: "CL",
//     leaveTypeName: "Casual Leave",
//     fromDate: "2026-05-11",
//     toDate: "2026-05-11",
//     dayType: "SECOND_HALF",
//     days: 0.5,
//     reason: "Bank appointment",
//     status: "APPROVED",
//     appliedOn: "2026-05-03",
//   },
//   {
//     id: "lv-1004",
//     employeeId: "emp-100",
//     employeeCode: "PNI001",
//     employeeName: "Aarav Menon",
//     department: "Engineering",
//     location: "Bengaluru",
//     managerId: "emp-200",
//     managerName: "Nisha Rao",
//     leaveTypeId: "lt-co",
//     leaveTypeCode: "CO",
//     leaveTypeName: "Comp Off",
//     fromDate: "2026-05-22",
//     toDate: "2026-05-22",
//     dayType: "FULL_DAY",
//     days: 1,
//     reason: "Comp off against weekend hiring drive",
//     status: "PENDING",
//     appliedOn: "2026-05-08",
//   },
//   {
//     id: "lv-1005",
//     employeeId: "emp-100",
//     employeeCode: "PNI001",
//     employeeName: "Aarav Menon",
//     department: "Engineering",
//     location: "Bengaluru",
//     managerId: "emp-200",
//     managerName: "Nisha Rao",
//     leaveTypeId: "lt-lop",
//     leaveTypeCode: "LOP",
//     leaveTypeName: "Loss Of Pay",
//     fromDate: "2026-04-29",
//     toDate: "2026-04-30",
//     dayType: "FULL_DAY",
//     days: 2,
//     reason: "Personal travel",
//     status: "CANCEL_REQUESTED",
//     appliedOn: "2026-04-20",
//   },
//   {
//     id: "lv-1006",
//     employeeId: "emp-100",
//     employeeCode: "PNI001",
//     employeeName: "Aarav Menon",
//     department: "Engineering",
//     location: "Bengaluru",
//     managerId: "emp-200",
//     managerName: "Nisha Rao",
//     leaveTypeId: "lt-oh",
//     leaveTypeCode: "OH",
//     leaveTypeName: "Optional Holiday",
//     fromDate: "2026-08-14",
//     toDate: "2026-08-14",
//     dayType: "FULL_DAY",
//     days: 1,
//     reason: "Optional holiday before Independence Day weekend",
//     status: "REJECTED",
//     appliedOn: "2026-05-01",
//     approverRemarks: "Team coverage required.",
//   },
//   {
//     id: "lv-1007",
//     employeeId: "emp-100",
//     employeeCode: "PNI001",
//     employeeName: "Aarav Menon",
//     department: "Engineering",
//     location: "Bengaluru",
//     managerId: "emp-200",
//     managerName: "Nisha Rao",
//     leaveTypeId: "lt-cl",
//     leaveTypeCode: "CL",
//     leaveTypeName: "Casual Leave",
//     fromDate: "2026-06-03",
//     toDate: "2026-06-03",
//     dayType: "FULL_DAY",
//     days: 1,
//     reason: "Personal work",
//     status: "DRAFT",
//     appliedOn: "2026-05-09",
//   },
//   {
//     id: "lv-1008",
//     employeeId: "emp-101",
//     employeeCode: "PNI014",
//     employeeName: "Meera Krishnan",
//     department: "Engineering",
//     location: "Bengaluru",
//     managerId: "emp-200",
//     managerName: "Nisha Rao",
//     leaveTypeId: "lt-el",
//     leaveTypeCode: "EL",
//     leaveTypeName: "Earned Leave",
//     fromDate: "2026-05-19",
//     toDate: "2026-05-23",
//     dayType: "FULL_DAY",
//     days: 5,
//     reason: "Planned family travel",
//     status: "PENDING",
//     appliedOn: "2026-05-10",
//   },
//   {
//     id: "lv-1009",
//     employeeId: "emp-102",
//     employeeCode: "PNI022",
//     employeeName: "Rohan Iyer",
//     department: "Product",
//     location: "Pune",
//     managerId: "emp-200",
//     managerName: "Nisha Rao",
//     leaveTypeId: "lt-sl",
//     leaveTypeCode: "SL",
//     leaveTypeName: "Sick Leave",
//     fromDate: "2026-05-13",
//     toDate: "2026-05-14",
//     dayType: "FULL_DAY",
//     days: 2,
//     reason: "Medical recovery",
//     status: "PENDING",
//     appliedOn: "2026-05-12",
//   },
//   {
//     id: "lv-1010",
//     employeeId: "emp-103",
//     employeeCode: "PNI028",
//     employeeName: "Ananya Sharma",
//     department: "Design",
//     location: "Delhi NCR",
//     managerId: "emp-200",
//     managerName: "Nisha Rao",
//     leaveTypeId: "lt-cl",
//     leaveTypeCode: "CL",
//     leaveTypeName: "Casual Leave",
//     fromDate: "2026-06-01",
//     toDate: "2026-06-01",
//     dayType: "FIRST_HALF",
//     days: 0.5,
//     reason: "School admission appointment",
//     status: "PENDING_HR_VERIFICATION",
//     appliedOn: "2026-05-09",
//     approverRemarks: "Manager approved; pending HR verification.",
//   },
//   {
//     id: "lv-1011",
//     employeeId: "emp-104",
//     employeeCode: "PNI041",
//     employeeName: "Karthik Subramanian",
//     department: "Operations",
//     location: "Chennai",
//     managerId: "emp-201",
//     managerName: "Vikram Desai",
//     leaveTypeId: "lt-el",
//     leaveTypeCode: "EL",
//     leaveTypeName: "Earned Leave",
//     fromDate: "2026-05-19",
//     toDate: "2026-05-20",
//     dayType: "FULL_DAY",
//     days: 2,
//     reason: "Personal travel",
//     status: "PENDING",
//     appliedOn: "2026-05-11",
//   },
// ];

// export const mockLeaveBalances: LeaveBalance[] = [
//   {
//     employeeId: "emp-100",
//     employeeName: "Aarav Menon",
//     leaveTypeId: "lt-el",
//     leaveTypeCode: "EL",
//     leaveTypeName: "Earned Leave",
//     opening: 6,
//     credited: 5,
//     availed: 2,
//     pending: 3,
//     adjusted: 0,
//     balance: 6,
//     year: 2026,
//   },
//   {
//     employeeId: "emp-100",
//     employeeName: "Aarav Menon",
//     leaveTypeId: "lt-sl",
//     leaveTypeCode: "SL",
//     leaveTypeName: "Sick Leave",
//     opening: 4,
//     credited: 3,
//     availed: 1,
//     pending: 0,
//     adjusted: 0,
//     balance: 6,
//     year: 2026,
//   },
//   {
//     employeeId: "emp-100",
//     employeeName: "Aarav Menon",
//     leaveTypeId: "lt-cl",
//     leaveTypeCode: "CL",
//     leaveTypeName: "Casual Leave",
//     opening: 2,
//     credited: 2,
//     availed: 1,
//     pending: 0,
//     adjusted: 0,
//     balance: 3,
//     year: 2026,
//   },
//   {
//     employeeId: "emp-100",
//     employeeName: "Aarav Menon",
//     leaveTypeId: "lt-co",
//     leaveTypeCode: "CO",
//     leaveTypeName: "Comp-Off",
//     opening: 1,
//     credited: 2,
//     availed: 1,
//     pending: 1,
//     adjusted: 0,
//     balance: 1,
//     year: 2026,
//   },
//   {
//     employeeId: "emp-100",
//     employeeName: "Aarav Menon",
//     leaveTypeId: "lt-oh",
//     leaveTypeCode: "OH",
//     leaveTypeName: "Optional Holiday",
//     opening: 0,
//     credited: 2,
//     availed: 0,
//     pending: 0,
//     adjusted: 0,
//     balance: 2,
//     year: 2026,
//   },
// ];

// export const mockLeaveLedger: LeaveLedgerEntry[] = [
//   {
//     id: "ll-1",
//     employeeId: "emp-100",
//     leaveTypeId: "lt-el",
//     transactionDate: "2026-01-01",
//     transactionType: "CREDIT",
//     days: 6,
//     remarks: "Opening balance",
//   },
//   {
//     id: "ll-2",
//     employeeId: "emp-100",
//     leaveTypeId: "lt-el",
//     transactionDate: "2026-04-12",
//     transactionType: "DEBIT",
//     days: 2,
//     referenceId: "lv-0998",
//     remarks: "Approved leave debit",
//   },
// ];

// export const mockHolidayCalendars: HolidayCalendar[] = [
//   {
//     id: "hc-india-2026",
//     name: "India Holiday Calendar 2026",
//     year: 2026,
//     locations: [
//       "Ahmedabad",
//       "Bengaluru",
//       "Chandigarh",
//       "Chennai",
//       "Delhi NCR",
//       "Hyderabad",
//       "Jaipur",
//       "Kochi",
//       "Kolkata",
//       "Mumbai",
//       "Pune",
//     ],
//     holidays: [
//       {
//         id: "h-jan-26",
//         name: "Republic Day",
//         date: "2026-01-26",
//         type: "PUBLIC",
//         location: "All India",
//       },
//       {
//         id: "h-feb-19",
//         name: "Chhatrapati Shivaji Maharaj Jayanti",
//         date: "2026-02-19",
//         type: "OPTIONAL",
//         location: "Mumbai, Pune",
//       },
//       {
//         id: "h-feb-24",
//         name: "Maha Shivratri",
//         date: "2026-02-24",
//         type: "OPTIONAL",
//         location: "Ahmedabad, Bengaluru, Chandigarh, Delhi NCR, Jaipur, Mumbai, Pune",
//       },
//       {
//         id: "h-mar-04",
//         name: "Holi",
//         date: "2026-03-04",
//         type: "PUBLIC",
//         location: "Ahmedabad, Chandigarh, Delhi NCR, Jaipur, Kolkata, Mumbai, Pune",
//       },
//       {
//         id: "h-mar-19",
//         name: "Ramzan / Eid-ul-Fitr",
//         date: "2026-03-19",
//         type: "OPTIONAL",
//         location: "All Branches",
//       },
//       {
//         id: "h-mar-21",
//         name: "Ugadi / Gudi Padwa",
//         date: "2026-03-21",
//         type: "RESTRICTED",
//         location: "Bengaluru, Hyderabad, Mumbai, Pune",
//       },
//       {
//         id: "h-apr-03",
//         name: "Good Friday",
//         date: "2026-04-03",
//         type: "PUBLIC",
//         location: "Bengaluru, Chennai, Kochi, Kolkata, Mumbai, Pune",
//       },
//       {
//         id: "h-apr-14",
//         name: "Tamil New Year / Vishu",
//         date: "2026-04-14",
//         type: "RESTRICTED",
//         location: "Chennai, Kochi",
//       },
//       {
//         id: "h-apr-15",
//         name: "Bengali New Year",
//         date: "2026-04-15",
//         type: "OPTIONAL",
//         location: "Kolkata",
//       },
//       {
//         id: "h-apr-18",
//         name: "Mahavir Jayanti",
//         date: "2026-04-18",
//         type: "OPTIONAL",
//         location: "Ahmedabad, Delhi NCR, Jaipur, Mumbai, Pune",
//       },
//       {
//         id: "h-may-01",
//         name: "Labour Day",
//         date: "2026-05-01",
//         type: "COMPANY",
//         location: "All Branches",
//       },
//       {
//         id: "h-may-09",
//         name: "Maharana Pratap Jayanti",
//         date: "2026-05-09",
//         type: "OPTIONAL",
//         location: "Jaipur",
//       },
//       {
//         id: "h-jun-17",
//         name: "Bakrid",
//         date: "2026-06-17",
//         type: "OPTIONAL",
//         location: "All Branches",
//       },
//       {
//         id: "h-jul-16",
//         name: "Muharram",
//         date: "2026-07-16",
//         type: "OPTIONAL",
//         location: "Bengaluru, Chennai, Delhi NCR, Hyderabad, Kochi, Kolkata, Mumbai, Pune",
//       },
//       {
//         id: "h-aug-15",
//         name: "Independence Day",
//         date: "2026-08-15",
//         type: "PUBLIC",
//         location: "All India",
//       },
//       {
//         id: "h-aug-14",
//         name: "Varalakshmi Vratam",
//         date: "2026-08-14",
//         type: "OPTIONAL",
//         location: "Bengaluru, Chennai, Hyderabad",
//       },
//       {
//         id: "h-aug-16",
//         name: "Parsi New Year",
//         date: "2026-08-16",
//         type: "OPTIONAL",
//         location: "Ahmedabad, Mumbai, Pune",
//       },
//       {
//         id: "h-aug-28",
//         name: "Onam",
//         date: "2026-08-28",
//         type: "RESTRICTED",
//         location: "Kochi, Bengaluru, Chennai",
//       },
//       {
//         id: "h-sep-05",
//         name: "Milad-un-Nabi",
//         date: "2026-09-05",
//         type: "OPTIONAL",
//         location: "All Branches",
//       },
//       {
//         id: "h-sep-14",
//         name: "Ganesh Chaturthi",
//         date: "2026-09-14",
//         type: "OPTIONAL",
//         location: "Mumbai, Pune, Ahmedabad, Bengaluru, Hyderabad",
//       },
//       {
//         id: "h-sep-21",
//         name: "Mahalaya",
//         date: "2026-09-21",
//         type: "OPTIONAL",
//         location: "Kolkata",
//       },
//       {
//         id: "h-oct-02",
//         name: "Gandhi Jayanti",
//         date: "2026-10-02",
//         type: "PUBLIC",
//         location: "All India",
//       },
//       {
//         id: "h-oct-19",
//         name: "Durga Puja",
//         date: "2026-10-19",
//         type: "OPTIONAL",
//         location: "Kolkata, Delhi NCR",
//       },
//       {
//         id: "h-oct-20",
//         name: "Dussehra",
//         date: "2026-10-20",
//         type: "PUBLIC",
//         location: "All India",
//       },
//       {
//         id: "h-oct-26",
//         name: "Lakshmi Puja",
//         date: "2026-10-26",
//         type: "RESTRICTED",
//         location: "Kolkata, Delhi NCR, Jaipur",
//       },
//       {
//         id: "h-nov-01",
//         name: "Karnataka Rajyotsava",
//         date: "2026-11-01",
//         type: "OPTIONAL",
//         location: "Bengaluru",
//       },
//       {
//         id: "h-nov-08",
//         name: "Diwali",
//         date: "2026-11-08",
//         type: "PUBLIC",
//         location: "All India",
//       },
//       {
//         id: "h-nov-09",
//         name: "Govardhan Puja",
//         date: "2026-11-09",
//         type: "OPTIONAL",
//         location: "Ahmedabad, Delhi NCR, Jaipur, Mumbai, Pune",
//       },
//       {
//         id: "h-nov-10",
//         name: "Bhai Dooj",
//         date: "2026-11-10",
//         type: "OPTIONAL",
//         location: "Ahmedabad, Chandigarh, Delhi NCR, Jaipur, Mumbai, Pune",
//       },
//       {
//         id: "h-nov-24",
//         name: "Guru Nanak Jayanti",
//         date: "2026-11-24",
//         type: "RESTRICTED",
//         location: "Chandigarh, Delhi NCR, Jaipur",
//       },
//       {
//         id: "h-dec-01",
//         name: "State Formation Day",
//         date: "2026-12-01",
//         type: "OPTIONAL",
//         location: "Hyderabad",
//       },
//       {
//         id: "h-dec-24",
//         name: "Christmas Eve",
//         date: "2026-12-24",
//         type: "OPTIONAL",
//         location: "All Branches",
//       },
//       {
//         id: "h-dec-25",
//         name: "Christmas",
//         date: "2026-12-25",
//         type: "PUBLIC",
//         location: "All India",
//       },
//     ],
//   },
// ];

// export const mockCompOffCredits: CompOffCredit[] = [
//   {
//     id: "co-cred-101",
//     employeeId: "emp-100",
//     workedDate: "2026-04-18",
//     workedSession: "FULL_DAY",
//     creditedDays: 1,
//     expiryDate: "2026-07-18",
//     status: "AVAILABLE",
//     reason: "Weekend release support",
//     approvedBy: "Nisha Rao",
//   },
//   {
//     id: "co-cred-102",
//     employeeId: "emp-100",
//     workedDate: "2026-03-29",
//     workedSession: "SECOND_HALF",
//     creditedDays: 0.5,
//     expiryDate: "2026-06-29",
//     status: "AVAILED",
//     reason: "Production hotfix",
//     approvedBy: "Nisha Rao",
//   },
// ];

// export const mockCompOffCreditRequests: CompOffCreditRequest[] = [
//   {
//     id: "co-req-201",
//     employeeId: "emp-100",
//     workedDate: "2026-05-02",
//     workedSession: "FULL_DAY",
//     requestedDays: 1,
//     reason: "Hiring drive support",
//     status: "PENDING",
//     submittedOn: "2026-05-03",
//     approver: "Nisha Rao",
//   },
//   {
//     id: "co-req-202",
//     employeeId: "emp-100",
//     workedDate: "2026-02-15",
//     workedSession: "FIRST_HALF",
//     requestedDays: 0.5,
//     reason: "Client demo support",
//     status: "APPROVED",
//     submittedOn: "2026-02-16",
//     approver: "Nisha Rao",
//   },
// ];

// export const mockTeamCalendar: TeamCalendarEntry[] = mockLeaveRequests.map(
//   (request) => ({
//     id: `tc-${request.id}`,
//     employeeId: request.employeeId,
//     employeeName: request.employeeName,
//     department: request.department,
//     leaveTypeCode: request.leaveTypeCode,
//     fromDate: request.fromDate,
//     toDate: request.toDate,
//     status: request.status,
//   }),
// );

// export const mockLeavePolicies: LeavePolicy[] = [
//   {
//     id: "lp-el-2026",
//     name: "Earned Leave Policy - India",
//     leaveTypeId: "lt-el",
//     appliesTo: "All confirmed employees",
//     accrualFrequency: "MONTHLY",
//     annualEntitlement: 18,
//     carryForwardLimit: 30,
//     encashable: true,
//     active: true,
//   },
//   {
//     id: "lp-sl-2026",
//     name: "Sick Leave Policy - India",
//     leaveTypeId: "lt-sl",
//     appliesTo: "All employees",
//     accrualFrequency: "YEARLY",
//     annualEntitlement: 12,
//     carryForwardLimit: 0,
//     encashable: false,
//     active: true,
//   },
// ];

// export const mockWorkCalendars: WorkCalendar[] = [
//   {
//     id: "wc-ind-5day",
//     name: "India 5 Day Work Week",
//     locations: ["Bengaluru", "Chennai", "Hyderabad", "Mumbai", "Pune"],
//     weeklyOffs: ["SATURDAY", "SUNDAY"],
//     workingHoursPerDay: 8,
//     active: true,
//   },
//   {
//     id: "wc-ops-6day",
//     name: "Operations 6 Day Work Week",
//     locations: ["Mumbai", "Pune"],
//     weeklyOffs: ["SUNDAY"],
//     workingHoursPerDay: 8,
//     active: true,
//   },
// ];

// export const mockPayrollLeaveInputs: PayrollLeaveInput[] = [
//   {
//     id: "pli-2026-04-100",
//     employeeId: "emp-100",
//     employeeCode: "PNI001",
//     employeeName: "Aarav Menon",
//     month: "2026-04",
//     lopDays: 0,
//     paidLeaveDays: 2,
//     // compOffDays: 0,
//     remarks: "Ready for payroll",
//   },
//   {
//     id: "pli-2026-04-104",
//     employeeId: "emp-104",
//     employeeCode: "PNI041",
//     employeeName: "Karthik Subramanian",
//     month: "2026-04",
//     lopDays: 2,
//     paidLeaveDays: 0,
//     compOffDays: 0,
//     remarks: "Pending cancellation review",
//   },
// ];
