@api_base_url=https://pnc-hr1.auvitapps.com:7091/api


###
# @name admin_login
POST {{api_base_url}}/auth/login
Content-Type: application/json

{
    "loginId": "admin@pinnaclesystems.com",
    "password": "admin1234"
}

###
# @name hr_login
POST {{api_base_url}}/auth/login
Content-Type: application/json

{
    "loginId": "hr@pinnaclesystems.com",
    "password": "password"
}

###
# @name manager_login
POST {{api_base_url}}/auth/login
Content-Type: application/json

{
    "loginId": "manager@pinnaclesystems.com",
    "password": "password"
}

###
# @name employee_login
POST {{api_base_url}}/auth/login
Content-Type: application/json 

{
    "loginId": "employee@pinnaclesystems.com",
    "password": "password"
}
###
@access_token={{admin_login.response.body.data.accessToken}}
@employee_id=b0000000-0000-0000-0000-000000000004
@leave_request_id=c7d11ea2-2f72-41fa-9ca1-f5c66323e981
@leave_type_id=a255278d-22f9-40a7-a090-6708b5ef8e14
@leave_policy_id=efea2d7e-719b-4ece-baf6-8eddec73ef73
@holiday_calendar_id=2a135152-a44e-4c47-aa24-b7ab473cd19d
@holiday_id=REPLACE_WITH_HOLIDAY_ID
@work_calendar_id=556e4196-b1f2-44bc-80f1-9d85648cdf4a
@comp_off_id=7df057cf-784b-4c37-8be7-1fabfc341af6
@leave_year=2026

###
# @name get_leaves
GET {{api_base_url}}/leaves?page=0&size=20&sort=createdAt,DESC
Authorization: Bearer {{access_token}}

###
# @name get_leave_by_id
GET {{api_base_url}}/leaves/{{leave_request_id}}
Authorization: Bearer {{access_token}}

###
# @name get_leave_types
GET {{api_base_url}}/leave-types?page=0&size=50&sort=name,ASC
Authorization: Bearer {{access_token}}

###
# @name get_leave_type_by_id
GET {{api_base_url}}/leave-types/{{leave_type_id}}
Authorization: Bearer {{access_token}}

###
# @name get_leave_policies
GET {{api_base_url}}/leave-policies?page=0&size=20
Authorization: Bearer {{access_token}}

###
# @name get_leave_policy_by_id
GET {{api_base_url}}/leave-policies/{{leave_policy_id}}
Authorization: Bearer {{access_token}}

###
# @name get_leave_policy_rules
GET {{api_base_url}}/leave-policy-rules?page=0&size=20
Authorization: Bearer {{access_token}}

###
# @name get_holiday_calendars
GET {{api_base_url}}/holiday-calendars?page=0&size=20
Authorization: Bearer {{access_token}}

###
# @name get_holiday_calendar_by_id
GET {{api_base_url}}/holiday-calendars/{{holiday_calendar_id}}
Authorization: Bearer {{access_token}}

###
# @name get_holidays
GET {{api_base_url}}/holidays?page=0&size=50
Authorization: Bearer {{access_token}}

###
# @name get_work_calendars
GET {{api_base_url}}/work-calendars?page=0&size=20
Authorization: Bearer {{access_token}}

###
# @name get_work_calendar_by_id
GET {{api_base_url}}/work-calendars/{{work_calendar_id}}
Authorization: Bearer {{access_token}}

###
# @name get_comp_offs
GET {{api_base_url}}/comp-offs?page=0&size=20
Authorization: Bearer {{access_token}}

###
# @name get_comp_off_by_id
GET {{api_base_url}}/comp-offs/{{comp_off_id}}
Authorization: Bearer {{access_token}}

###
# @name get_employee_leave_balances
GET {{api_base_url}}/employees/{{employee_id}}/leave-balances?leaveYear={{leave_year}}
Authorization: Bearer {{access_token}}

###
# @name get_employee_leave_ledger
GET {{api_base_url}}/employees/{{employee_id}}/leave-ledger?leaveTypeId={{leave_type_id}}
Authorization: Bearer {{access_token}}

###
# @name get_payroll_leave_summary
GET {{api_base_url}}/payroll/leave-summary
Authorization: Bearer {{access_token}}

###
# @name download_template
GET {{api_base_url}}/employees/bulk-upload/template
Authorization: Bearer {{access_token}}
Accept: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

###