export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh-token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    PROFILE: "/auth/profile",
    VERIFY_OTP: "/auth/verify-otp",
    MFA_VERIFY: "/auth/mfa/verify",
    MFA_SETUP: "/auth/mfa/setup",
    MFA_RESENDOTP: "/auth/mfa/resend-otp",
    MFA_ENABLE: "/auth/mfa/enable",
    CHANGE_PASSWORD: "/auth/change-password",
    SELECT_TENANT: "/auth/login/select-tenant",
    SET_PASSWORD: "/auth/set-password",
    PERMISSIONS: "/auth/permissions",
    PHOTO: "/auth/profile/picture",
  },

  LOGIN_HISTORY: {
    DELETE: "/login-history",
    CLEAR_OLDER: (days: string) => `/login-history/older-than/${days}`,
    BASE: "/login-history",
    GET_BY_USERID: (id: string) => `/login-history/user/${id}`,
    GET_BY_TENANTID: "/login-history/tenant"
  },

  BRANCH: {
    BASE: "/org/branches",
    GET_BY_ID: (id: string) => `/org/branches/${id}`,
    CREATE: "/org/branches",
    GET_ACTIVE: "/org/branches/active",
    UPDATE: (id: string) => `/org/branches/${id}`,
    DELETE: (id: string) => `/org/branches/${id}`,
    PATCH: (id: string) => `/org/branches/${id}/toggle-active`,
  },

  DEPARTMENT: {
    DELETE: (id: string) => `/org/departments/${id}`,
    GET_BY_ID: (id: string) => `/org/departments/${id}`,
    BASE: "/org/departments",
    GET_BY_BRANCHID: (bid: string) => `/org/departments/by-branch/${bid}`,
    GET_ACTIVE: "/org/departments/active",
    PATCH: (id: string) => `/org/departments/${id}/toggle-active`,
    CREATE: "/org/departments",
    UPDATE: (id: string) => `/org/departments/${id}`,
  },

  CATEGORY: {
    DELETECAT: (id: string) => `/org/category/${id}`,
    DELETECATITEM: (id: string, cid: string) => `/org/category/${cid}/items/${id}`,
    GET_BY_CATID: (id: string) => `/org/category/${id}`,
    GET_BY_CATITEMID: (id: string, cid: string) => `/org/category/${cid}/items/${id}`,
    BASECAT: "/org/category",
    BASECATITEM: (cid: string) => `/org/category/${cid}/items`,
    PATCHCAT: (cid: string) => `/org/category/${cid}/toggle-enabled`,
    PATCHCATITEM: (id: string, cid: string) => `/org/category/${cid}/items/${id}/toggle-active`,
    CREATECAT: "/org/category",
    CREATECATITEM: (cid: string) => `/org/category/${cid}/items`,
    UPDATECAT: (id: string) => `/org/category/${id}`,
    UPDATECATITEM: (id: string, cid: string) => `/org/category/${cid}/items/${id}`,
  },

  COMPANY: {
    DELETE: (id: string) => `/org/company/${id}`,
    GET_BY_ID: (id: string) => `/org/company/${id}`,
    BASE: "/org/company",
    CREATE: "/org/company",
    UPDATE: (id: string) => `/org/company/${id}`,
    UPLOAD_LOGO: (id: string) => `/org/company/${id}/logo`,
    UPLOAD_SIGNATURE: (id: string) => `/org/company/${id}/signature`,
  },

  EMPLOYEE: {
    DELETE: (id: string) => `/employees/${id}`,
    DELETE_TRAINING: (id: string, tid: string) => `/employees/${id}/training-details/${tid}`,
    DELETE_QUALIFICATION: (id: string, qid: string) => `/employees/${id}/qualifications/${qid}`,
    DELETE_PRE_EMP: (id: string, pid: string) => `/employees/${id}/previous-employments/${pid}`,
    DELETE_PF: (id: string, pid: string) => `/employees/${id}/pf-accounts/${pid}`,
    DELETE_NOMINATION: (id: string, nid: string) => `/employees/${id}/nominations/${nid}`,
    DELETE_FAMILY: (id: string, fid: string) => `/employees/${id}/family-members/${fid}`,
    DELETE_EMERGENCY: (id: string, eid: string) => `/employees/${id}/emergency-contacts/${eid}`,
    DELETE_ADDRESS: (id: string, aid: string) => `/employees/${id}/addresses/${aid}`,
    DELETE_ATTACHMENT: (id: string, aid: string) => `/employees/${id}/attachments/${aid}`,

    GET_BY_ID: (id: string) => `/employees/${id}`,
    BASE: "/employees",
    GET_TRAINING: (id: string) => `/employees/${id}/training-details`,
    GET_QUALIFICATION: (id: string) => `/employees/${id}/qualifications`,
    GET_PRE_EMP: (id: string) => `/employees/${id}/previous-employments`,
    GET_PF: (id: string) => `/employees/${id}/pf-accounts`,
    GET_NOMINATION: (id: string) => `/employees/${id}/nominations`,
    GET_FAMILY: (id: string) => `/employees/${id}/family-members`,
    GET_EMERGENCY: (id: string) => `/employees/${id}/emergency-contacts`,
    GET_ADDRESS: (id: string) => `/employees/${id}/addresses`,
    GET_ATTACHMENT: (id: string) => `/employees/${id}/attachments`,

    PATCH_PF: (id: string) => `/employees/${id}/pf`,
    PATCH_PERSONAL: (id: string) => `/employees/${id}/personal`,
    PATCH_IDENTITY: (id: string) => `/employees/${id}/identity`,
    PATCH_BANK: (id: string) => `/employees/${id}/bank`,
    PATCH_BG: (id: string) => `/employees/${id}/background`,
    PATCH_ADMIN: (id: string) => `/employees/${id}/admin`,

    CREATE: "/employees",
    POST_TRAINING: (id: string) => `/employees/${id}/training-details`,
    POST_QUALIFICATION: (id: string) => `/employees/${id}/qualifications`,
    POST_PRE_EMP: (id: string) => `/employees/${id}/previous-employments`,
    UPLOAD_PHOTO: (id: string) => `/employees/${id}/photo`,
    POST_PF: (id: string) => `/employees/${id}/pf-accounts`,
    POST_NOMINATION: (id: string) => `/employees/${id}/nominations`,
    POST_FAMILY: (id: string) => `/employees/${id}/family-members`,
    POST_EMERGENCY: (id: string) => `/employees/${id}/emergency-contacts`,
    POST_ADDRESS: (id: string) => `/employees/${id}/addresses`,
    POST_ATTACHMENT: (id: string) => `/employees/${id}/attachments`,
    BULK_UPLOAD: "/employees/bulk-upload",

    UPDATE: (id: string) => `/employees/${id}`,
    UPDATE_TRAINING: (id: string, tid: string) => `/employees/${id}/training-details/${tid}`,
    UPDATE_QUALIFICATION: (id: string, qid: string) => `/employees/${id}/qualifications/${qid}`,
    UPDATE_PRE_EMP: (id: string, pid: string) => `/employees/${id}/previous-employments/${pid}`,
    UPDATE_PF: (id: string, pid: string) => `/employees/${id}/pf-accounts/${pid}`,
    UPDATE_NOMINATION: (id: string, nid: string) => `/employees/${id}/nominations/${nid}`,
    UPDATE_FAMILY: (id: string, fid: string) => `/employees/${id}/family-members/${fid}`,
    UPDATE_EMERGENCY: (id: string, eid: string) => `/employees/${id}/emergency-contacts/${eid}`,
    UPDATE_ADDRESS: (id: string, aid: string) => `/employees/${id}/addresses/${aid}`,
  },

  MASTER: {
    GET_CITY: "/master/cities",
    GET_COUNTRY:"/master/countries",
    GET_STATES:"/master/states",
    GET_CURRENCIES:"/master/currencies",
    GET_STATES_BY_COUNTRY: (cid:any) => `/master/states/by-country/${cid}`,
    GET_CITIES_BY_COUNTRY: (cid:any) => `/master/cities/by-country/${cid}`,
    GET_CITIES_BY_STATE: (sid:any) => `/master/cities/by-state/${sid}`
  }
};
