export const PERMISSIONS = {
  // Employee permissions
  EMPLOYEE_READ: 'EMPLOYEE_READ',
  EMPLOYEE_WRITE: 'EMPLOYEE_WRITE',
  EMPLOYEE_DELETE: 'EMPLOYEE_DELETE',
  EMPLOYEE_UPLOAD: 'EMPLOYEE_UPLOAD',

  // Payroll permissions
  PAYROLL_READ: 'PAYROLL_READ',
  PAYROLL_WRITE: 'PAYROLL_WRITE',

  // Report permissions
  REPORT_READ: 'REPORT_READ',
  REPORT_EXPORT: 'REPORT_EXPORT',

  // Profile permissions
  PROFILE_READ: 'PROFILE_READ',
  PROFILE_WRITE: 'PROFILE_WRITE',

  // Settings
  SETTINGS_READ: 'SETTINGS_READ',
  SETTINGS_WRITE: 'SETTINGS_WRITE',

  // Policy
  POLICY_READ: 'POLICY_READ',
  POLICY_WRITE: 'POLICY_WRITE',

  // Attendance
  ATTENDANCE_READ: 'ATTENDANCE_READ',
  ATTENDANCE_WRITE: 'ATTENDANCE_WRITE',

  // Leave
  LEAVE_READ: 'LEAVE_READ',
  LEAVE_WRITE: 'LEAVE_WRITE',
  LEAVE_APPROVE: 'LEAVE_APPROVE',

  // Admin permissions
  USER_MANAGE: 'USER_MANAGE',
  ROLE_MANAGE: 'ROLE_MANAGE',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];


// HR
// EMPLOYEE_READ
// EMPLOYEE_WRITE
// EMPLOYEE_DELETE
// EMPLOYEE_UPLOAD
// PAYROLL_READ
// PAYROLL_WRITE
// REPORT_READ
// REPORT_EXPORT
// PROFILE_READ
// PROFILE_WRITE
// SETTINGS_READ
// SETTINGS_WRITE
// POLICY_READ  
// POLICY_WRITE
// ATTENDANCE_WRITE
// ATTENDANCE_READ
// LEAVE_READ
// LEAVE_WRITE
// LEAVE_APPROVE

// ADMIN
// PAYROLL_READ
// PAYROLL_WRITE
// REPORT_EXPORT
// REPORT_READ
// PROFILE_READ
// PROFILE_WRITE
// SETTINGS_READ
// SETTINGS_WRITE
// POLICY_READ
// POLICY_WRITE
// ATTENDANCE_WRITE
// ATTENDANCE_READ
// LEAVE_READ
// LEAVE_WRITE
// LEAVE_APPROVE
// USER_MANAGE
// ROLE_MANAGE

// MANAGER
// PAYROLL_READ
// EMPLOYEE_READ
// EMPLOYEE_WRITE
// EMPLOYEE_DELETE
// EMPLOYEE_UPLOAD
// REPORT_READ
// PROFILE_READ
// PROFILE_WRITE
// PROFILE_READ
// PROFILE_WRITE
// ATTENDANCE_READ
// LEAVE_READ
// LEAVE_WRITE
// LEAVE_APPROVE

// ESS
// PAYROLL_READ
// EMPLOYEE_READ
// EMPLOYEE_WRITE
// EMPLOYEE_DELETE
// EMPLOYEE_UPLOAD
// REPORT_READ
// PROFILE_READ
// PROFILE_WRITE
// ATTENDANCE_READ
// LEAVE_READ
// LEAVE_WRITE
